name: cron

on:
  schedule:
    - cron: '5 3 * * *'

jobs:
  build:
    name: Automated version refresher
    runs-on: ubuntu-latest
    steps:
      - name: Get their version
        run: THEIR_VERSION=$(curl -s "https://api.github.com/repos/anchore/grype/releases/latest" | grep "browser_download_url" | cut -d '"' -f 4 | cut -f 8 -d \/ | uniq)
      - name: Get our version
        run: OUR_VERSION=$(cat Dockerfile | grep install.sh | awk '{print $NF}')
      - name: Compare the versions and freshen if need be
        run: if [ "$THEIR_VERSION" = "$OUR_VERSION" ]; then echo no newer version found; else sed -i '/install.sh/ s/'$OUR_VERSION'/'$THEIR_VERSION'/' ./Dockerfile ; export FRESHEN=true fi
      - name: Freshen if need be
        run: if [ "$FRESHEN" = "true" ]; then git checkout -b freshen; git commit -am 'autorefreshen process'; git push fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          commit-message: automatic update
          title: Automatic Update
          body: The cronjob detected that grype had a release and is updating dependencies
          branch: freshen
          base: main
          delete-branch: true
      - name: merge the pull request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          number: ${{ steps.cpr.outputs.pull-request-number }} 
          method: squash
          repo: boxboat/grypeadmissioncontroller